import { Field } from "./Field";
import { PreferenceSelector } from "./PreferenceSelector";
import type { FinancialProfileForm, GoalForm } from "../types/financial";
import type { RankingPreference } from "../types/strategy";

type Props = { profile: FinancialProfileForm; goal: GoalForm; preference: RankingPreference; loading: boolean; onProfileChange: (key: keyof FinancialProfileForm, value: string) => void; onGoalChange: (key: keyof GoalForm, value: string) => void; onPreferenceChange: (value: RankingPreference) => void; onGenerate: () => void };

export function PlanningPanel({ profile, goal, preference, loading, onProfileChange, onGoalChange, onPreferenceChange, onGenerate }: Props) {
  const valid = Number(profile.income) > 0 && Number(profile.expenses) >= 0 && Number(profile.expenses) <= Number(profile.income) && Number(profile.savings) >= 0 && Number(profile.investments) >= 0 && Number(goal.amount) > 0 && goal.name.trim().length > 0;
  return <div className="panel form-panel"><div className="panel-heading"><div><p className="section-label">01 / YOUR STARTING POINT</p><h2>Build your financial context</h2></div><span className="step">1 of 2</span></div><div className="form-grid"><Field label="Monthly income" value={profile.income} onChange={value => onProfileChange("income", value)} /><Field label="Monthly expenses" value={profile.expenses} onChange={value => onProfileChange("expenses", value)} /><Field label="Cash savings" value={profile.savings} onChange={value => onProfileChange("savings", value)} /><Field label="Investments" value={profile.investments} onChange={value => onProfileChange("investments", value)} /></div><div className="control-grid"><SelectField label="Emergency reserve" value={profile.emergencyMonths} onChange={value => onProfileChange("emergencyMonths", value)} options={["3", "6", "9", "12"].map(value => ({ value, label: `${value} months` }))} /><SelectField label="Risk tolerance" value={profile.riskTolerance} onChange={value => onProfileChange("riskTolerance", value)} options={["low", "medium", "high"].map(value => ({ value, label: value }))} /></div><div className="goal-block"><p className="section-label">YOUR FINANCIAL GOAL</p><div className="goal-grid"><Field label="What are you planning?" value={goal.name} onChange={value => onGoalChange("name", value)} /><Field label="Target amount" value={goal.amount} onChange={value => onGoalChange("amount", value)} /></div><div className="control-grid"><SelectField label="Goal category" value={goal.category} onChange={value => onGoalChange("category", value)} options={["vehicle", "home", "land", "education", "business", "wedding", "medical", "custom"].map(value => ({ value, label: value }))} /><SelectField label="Timeline flexibility" value={goal.flexibility} onChange={value => onGoalChange("flexibility", value)} options={["low", "medium", "high"].map(value => ({ value, label: value }))} /></div></div><PreferenceSelector value={preference} onChange={onPreferenceChange} />{!valid && <p className="validation-message">Enter a valid income, expenses, savings, investment, and target amount to continue.</p>}<button className="primary" onClick={onGenerate} disabled={loading || !valid}>{loading ? "Running scenarios…" : "Generate top strategies  →"}</button></div>;
}

function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label className="field select-field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>; }
